chiselstrike/chiselstrike

server/src/datastore/crud.rs

Prerequisite to https://github.com/chiselstrike/chiselstrike/pull/1281 
Makes CRUD tests use query engine to provide better end-to-end coverage. It was very helpful when developing the above-mentioned PR and is imo worth the additional complexity.

Make CRUD tests use QueryEngine.

---

Cargo.lock
Cargo.toml
my_tsc/Cargo.toml
my_tsc/src/main.rs
tsc_compile/src/lib.rs

This is handy for debugging TSC. In particular, one can run
$ my_tsc --inspect test.ts
To easily debug TSC in chrome://inspect

Add a my_tsc utility

---

api/src/chisel.ts
cli/tests/lit/bad-filter.deno
cli/tests/lit/find.deno
docusaurus/docs/InDepth/advanced-data.md
docusaurus/docs/Intro/data-access.md

Adds support for `findMany(predicate lambda)`.

Implement findMany with predicate.

---

server/src/datastore/crud.rs
server/src/deno.rs

Moves crud query processing entirely to crud.rs. The functionality should be almost unchanged.
This PR is a part of a PR odyssey leading to paging (https://github.com/chiselstrike/chiselstrike/pull/1281)

Move CRUD querying logic to crud.rs. (but smaller)

---

api/src/chisel.ts
cli/tests/lit/find.deno

Extends `findOne` to support filtering with predicate lambda.

Implement findOne with predicate.

---

server/src/datastore/crud.rs

Refactors how CRUD parameters are being parsed. Prep work for #1282 .

crud.rs: Refactor parameter filter parsing.

---

tsc_compile/src/lib.rs

We don't need it anymore since deno_graph handles this transparently.

Remove extra_lib from DownloadMap

---

server/src/datastore/crud.rs

Simplifies stream creation in Crud.rs. Clippy and the compiler seem to be ok with the change.

crud.rs: Decontextualize query stream creation.

---

server/src/datastore/crud.rs

No functionality change, just more type safety.

Pass Url instead of str to a couple of functions

---

server/src/datastore/crud.rs

The Query structure is used as an intermediary between raw URL and
QueryPlan.

crud.rs: Introduce Query structure.

---

tsc_compile/src/lib.rs

I want to insert urls in the download map from other places, so
refactor it.

Refactor url insertion code

---

server/src/datastore/crud.rs

This PR simplifies the Query structure to be just a Query structure and not multi-purpose madness.

crud.rs: Remove referential garbage from Query.

---

server/src/datastore/crud.rs

Uses Url type directly in CrudParams, leaving the deserialization up to serde.

crud.rs: Use Url type directly in CrudParams.

---

tsc_compile/src/lib.rs
tsc_compile_build/src/tsc.js

Leaving as a draft since it goes on top of https://github.com/chiselstrike/chiselstrike/pull/1305.

Fix location

---

server/src/datastore/crud.rs

Simplifies stream handling in run_query. The main motivation is that paging requires the `Query` to be shared between result stream creation and then consumption and consequent handling.

crud.rs: simplify stream handling in run_query.

---

tsc_compile/src/lib.rs

With this we output the javascript corresponding to imported
typescript files.
The fix is done by changing write_impl to record more files and having
a post processing step that maps JS files to the TS files they came
from.
It is possible to do this in write_impl itself, but the post
processing version is simpler.
A followup PR will make write_impl trivial by doing all the work on
the post processing step.

Output compiled import files

---

cli/tests/lit/pol-anon.deno

It is simpler to filter the output with jq.

Drop defaultCreateResponse

---

tsc_compile/src/lib.rs

This includes two patches that should have no functionality change, they just simplify the code.

Simplify our TSC integration

---

docusaurus/package.json
docusaurus/yarn.lock

Update Docusaurus dependencies to fix some issues pointed out by `yarn
audit`.

Update Docusaurus dependencies

---

tsc_compile/src/lib.rs
tsc_compile_build/src/tsc.js

This is a bit of a hack as it requires dropping noEmitOnError and
working around TSC not wanting to override a .js.
I still think it is worth it, in part because it is a lot less code,
in part because it is closer to how deno calls TSC.

Don't map url to paths

---

cli/tests/lit/access-origin.deno
cli/tests/lit/endpoint-error.deno
cli/tests/lit/error-on-stream.deno
cli/tests/lit/infinite.deno
cli/tests/lit/pol-loggedin.deno
cli/tests/lit/populate.deno
cli/tests/lit/prefix.deno
cli/tests/lit/remove-endpoints.deno
cli/tests/lit/restart-js.deno
cli/tests/lit/store-nested-type.deno
cli/tests/lit/stream-db.deno
cli/tests/lit/transaction.deno
cli/tests/lit/url-query.deno
cli/tests/lit/use-module.deno
cli/tests/lit/use-ts-moduled.deno

A change I am working on will make us more strict about .js files
being javascript. These are fixes for the errors in the tests found by
that change.

Don't put TS in .js files

---

api/src/chisel.ts
api/src/worker.ts
server/src/datastore/crud.rs
server/src/datastore/query.rs
server/src/deno.rs

Adds headers to RequestContexts

---

server/src/datastore/crud.rs

Introduces sorting by id by default in CRUD.
Requested by @espindola . Prerequisite to #1281 .

crud.rs: Sort by id by default.

---

cli/tests/lit/crud.node
cli/tests/lit/pol-anon.deno
server/src/datastore/crud.rs
server/src/datastore/query.rs
server/src/deno.rs

Brings paging to CRUD.
I think that some things still remain to be done, namely:
I guess that 1) should be done in this PR, but I would do 2 and 3 in later PRs to minimize the size of this PR, it's pretty big anyway.

Introduce paging to CRUD.

---

api/src/chisel.ts
server/src/datastore/engine.rs

This simplifies processing it.

Don't flatten IdTree

---

api/src/chisel.ts

chisel.ts: rename makeQueryIter and makeTransformedQueryIter.

---

cli/tests/lit/crud.node
server/src/datastore/crud.rs

This PR brings "prev_page" to CRUD response. Builds upon #1281 
I've divided it into two commits, but I'll give it a thought after lunch and see if I can split it further to improve readability of this PR.
Also some rests to be done:

CRUD: Implement previous page

---

server/src/secrets.rs
server/src/server.rs

Also use a simple comparison to check if we have a new one. We already
have a copy of the secrets in each worker, so using a hash was not
saving much memory. getSecret was also already decripting the secrets,
so avoiding a json parse was also not saving that much cpu.
With this all errors getting secrets are handled uniformly.

Return a JsonObject from getSecret

---

perf/README.md
perf/backend/.gitignore
perf/backend/Chisel.toml
perf/backend/endpoints/find.ts
perf/backend/endpoints/fixture.ts
perf/backend/endpoints/users.ts
perf/backend/models/user.ts
perf/backend/package-lock.json
perf/backend/package.json
perf/backend/tsconfig.json

This adds a very simple application for benchmarking purposes. The main
benefit right now is the fixture setup using Faker.js, but we can keep
on improving this with more scenarios and more automation for comparing
performance.

Simple benchmark application

---

api/src/chisel.ts

I have fixed most type errors already. This fixes a null X undefined
error and adds a FIXME for the last one I know of.

Add type safe opSync and opAsync

---

chiselc/tests/lit/transform-filter-with-side-effects.lit

Test that transforming a filter with side-effects preseves the lambda.

chiselc: Add test for transforming filter with side-effects

---

server/src/server.rs

It is an open issue whether we want to treat failures in both
locations the same, but while we are, may as well do so from a single
function.

Refactor secret reading to a helper function

---

docusaurus/docs/InDepth/cursors.md

cursors.md: Add docs for sortBy, minBy, maxBy.

---

server/src/datastore/crud.rs

This PR replaces `page_after` and `page_before` CRUD param keys with a single unified `cursor` key. It simplifies the code and by making the paging direction completely opaque also decrees potential for user error. I originally thought that the explicit directionless will be better, but the use-cases are very limited and the additional complexity isn't worth it imo.
This is also aligned with the way Slack uses cursors and paging which was the main inspiration for our paging.

crud.rs: Replace page_after, page_before params with 'cursor'.

---

server/src/deno.rs

Adding a variable makes this code cleaner IMHO.

Small cleanup

---

perf/README.md
perf/backend/endpoints/array.ts
perf/backend/endpoints/base.ts
perf/backend/endpoints/bench.ts
perf/backend/endpoints/find.ts
perf/backend/endpoints/fixture.ts
perf/backend/endpoints/users.ts
perf/backend/models/user.ts

* adds an age field, so we can demonstrate range queries as well
* benchmarks from the release build
* make the fixture a bit smarter, and add the elements to be found there
for simplicity

change perf benchmark

---

chiselc/src/query.rs
chiselc/src/rewrite.rs
chiselc/src/transforms/utils.rs

Some cleanups to `chiselc` to make filter lambda splitting potentially easier.

chiselc cleanups

---

cli/tests/lit/secrets.deno
server/src/server.rs

I think this matches the description in:
https://github.com/chiselstrike/chiselstrike/issues/1375#issuecomment-1148780993

Don't clear secrets on IO error

---

cli/src/cmd/apply/deno.rs
cli/src/cmd/apply/node.rs
cli/src/project.rs

No functionality change. See the patches for the individual descriptions.

Two small refactorings

---

server/src/rpc.rs

From this point on we only need the paths, not the sources.
This reduces cloning the sources and helps a bit with a future change
where endpoint_routes is replaced with source map of all modules.

Don't clone sources more than needed

---

chiselc/tests/lit/filter_splitting/filter-with-side-effects.lit

Add a test case for splitting a logical and expression with three
sub-expressions.

chiselc: Test case for splitting larger expression

---

cli/src/cmd/dev.rs

We try to watch the policies, models and endpoints directories for
change, but that's not ideal.
First, from the crate's documentation:
```
On some platforms, if the path is renamed or removed while being
watched, behaviour may be unexpected. See discussions in 165 and 166.
If less surprising behaviour is wanted one may non-recursively watch the
parent directory as well and manage related events.
```
On top of that, if some of those directories don't exist when we
first invoke dev, watch will error out and `chisel dev` will fail (#1420)
Since those directories can be created later, Let's follow the crate's
suggestion and watch the entire directory, filtering out stuff we don't
want.
Fixes #1420

watch the base directory only when in dev mode

---

cli/src/cmd/apply/deno.rs
server/src/rpc.rs

For now the server ignores everything but the endpoints.

Send all modules to the server

---

Cargo.lock
server/Cargo.toml
server/src/datastore/crud.rs
server/src/deno.rs
server/src/secrets.rs

The build would break if these got out of sync anyway.

Use url from deno

---

packages/chiselstrike-api/package.json
packages/chiselstrike-cli/package.json
packages/create-chiselstrike-app/package.json

This updates the `package.json` files of our packages with up-to-date
metadata. In particular, links to Github and keywords are added for
discoverability.

packages: Update package.json metadata

---

api/src/chisel.ts

This is mostly Jan Plhak's work, I just simplified it a bit.
This changes the meaning of Operator<T> from something that produces
Ts to something that reads Ts. Neither is correct, but this at least
removes the most broken type assertion.
To make this sound we have to somehow map
class Foo extends Chisel.ChiselEntity {
bar: string = "";
zed: number = 0;
}
To
type Foo2 = {bar: string, zed: number}
Which is what is actually read from the DB. I don't see how to do that
with pure typescript.
To avoid all type assertions but the one when we actually read from
the DB, we need to somehow encode the op chain at the type system, so
that each recursive operation knows what type it consumes and
produces.

Fix some type assertions

---

cli/src/project.rs
cli/tests/lit/lib.deno

With the code import changes this is now trivial. If everyone is OK
with the design I will write some documentation.

Add a library directory to projects

---

cli/tests/lit/db-api.deno

This shows that we still have some bugs to fix until the types in
chisel.ts are sound.

Add a test documenting a bug

---

chiselc/src/transforms/utils.rs
chiselc/tests/lit/transform-filter-invalid.lit

Fix chiselc assertion crashes

---

server/src/datastore/engine.rs
server/src/deno.rs

Remove QueryEngine::mutate method

---

server/src/datastore/query.rs

Report entity name when it's not found

---

server/src/datastore/engine.rs
server/src/datastore/query.rs
server/src/policies.rs

Added hide transform policy to exclude sensitive or private fields from the returning json object

Added hide transform policy to exclude sensitive or private fields 

---

docusaurus/docs/Intro/endpoints.md

`.ts` extension is not allowed on import references

Minor code changes to make code compilable

---

Cargo.lock
server/Cargo.toml
server/src/main.rs
server/src/server.rs

On chiseld startup, attempts to read the config file from the platform specific
config directory, or from the file pointed to by the `-c` cli argument.

chiseld config file

---

cli/src/main.rs

followup https://github.com/chiselstrike/chiselstrike/pull/1523#discussion_r915744573

factorize dev and start server spawning

---

docusaurus/package.json
docusaurus/yarn.lock

Upgrade Docusaurus to address some security vulnerabilities reported by
Dependabot.

Upgrade Docusaurus to 2.0.0-beta.22

---

api/src/chisel.ts
cli/src/ts.rs
cli/tests/lit/store-nested-type.deno

Fixes the issue of replacing nested entities with plain records.

Warn about initialization of nested entities and fix shallow object.assign

---

api/src/chisel.ts

This PR adds aggregation operator used by `minBy` and `maxBy`. In consequent PRs, this operator will be shipped to our backend and evaluated directly in the database.
It's composed of three separate patches, so it might be better to go one by one.

Add aggregation operator.

---

cli/tests/lit/id.deno
cli/tests/test-wrapper.sh
server/src/types.rs

Fixes auto-indexing over `id` field. 
I've also enabled auto-indexing when testing with optimizations. We haven't been testing auto-indexing at all.

Fix auto index

---

cli/tests/lit/store-nested-type.deno

Followup on https://github.com/chiselstrike/chiselstrike/pull/1522

Test warning on uninitialized entity field.

---

cli/tests/chiseld_args.rs
cli/tests/common/mod.rs

This pr tests that we pass arguments correctly from cli to chiseld

cli test pass args to chiseld

---

api/src/chisel.ts
cli/tests/lit/find.deno

First little simplification and quality life improvement for our endpoints.
Introduces Query structure to simplify parsing and working with query string.

Query helper

---

cli/src/cmd/apply.rs
cli/src/cmd/apply/deno.rs
cli/src/cmd/apply/node.rs
cli/src/cmd/dev.rs
cli/src/project.rs
cli/src/ts.rs
cli/tests/lit/bad-url.deno
cli/tests/lit/endpoint-error.deno
cli/tests/lit/http-import.node
cli/tests/lit/parse-error.deno
cli/tests/lit/savewrong.deno
endpoint_tsc/src/lib.rs
server/src/datastore/crud.rs
server/src/datastore/dbconn.rs
server/src/datastore/meta/mod.rs
server/src/deno.rs
server/src/rpc.rs
server/src/secrets.rs
tsc_compile/src/lib.rs

While trying to debug imports, I found some confusing error messages. This PR aims to improve them.

Improve error messages

---

cli/tests/integration_tests.rs

As we try to get close to the "real" ports we use, by using algorithms
like 8080 + i, 9090 +i, etc, we end up clashing with lots of stuff,
potentially other chiseld.
This seems to work better, and tests start passing again.

Use higher ports for tests

---

packages/create-chiselstrike-app/index.ts

create-chiselstrike-app: Add .gitkeep to policies and models directories

---

chiselc/src/transforms/filter/emit.rs
chiselc/tests/lit/filter_splitting/filter-with-side-effects.lit
chiselc/tests/lit/transform-filter.lit

Closes https://github.com/chiselstrike/chiselstrike/issues/1562
It's really hacky though... Without types it's really hard to get it to be correct.

Fix chiselc's output for lambdas using local variables.

---

cli/src/cmd/apply/node.rs
cli/src/project.rs

There's currently a pretty serious problem with chiselc and endpoints
within subdirectories. The algorithm to figure out the name of the
generated file is to just take the filename() component of the endpoint
path, which has two big problems:
1. endpoints/foo/bar.ts will override endpoints/bar.ts in .gen.
2. import paths containing "../../" will not work.
The best way forward, especially because of relative paths for imports,
is to keep path structures the same, just replacing endpoints with .gen.
We'll have issues if the user uses either absolute paths or ./ as paths
in the manifest, but those are likely bad ideas (with the first
potentially being a security issue in the managed deployments) anyway.
So this patch also prevents them by checking early and making sure those
things are not …

make sure paths are respected within .gen

---

packages/create-chiselstrike-app/template/hello.ts

Since chiselstrike 0.11, this code can be simpler.

simplify hello endpoint

---

cli/src/cmd/apply.rs
cli/src/cmd/apply/deno.rs
cli/src/cmd/apply/node.rs

Minor code cleanups to the apply path to make it more readable.

Apply code cleanups

---

server/src/server.rs

It's pretty handy when debugging...

server: Show RPC address in startup logs

---

packages/create-chiselstrike-app/index.ts
packages/create-chiselstrike-app/template/README-template.md

create-chiselstrike-app: Generate README.md

---

cli/src/ts.rs
cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust_tests/test_array.rs
docusaurus/docs/Intro/first.md
proto/chisel.proto
server/src/datastore/crud.rs
server/src/datastore/engine.rs
server/src/rpc.rs
server/src/types.rs

Adds support for arrays of strings, numbers, booleans and arrays.

Implement support for arrays of primitive types.

---

cli/tests/integration_tests/chisel-macros/src/lib.rs

fully qualify test names to allow precise filtering.

fully qualified test names

---

cli/src/cmd/apply/node.rs

apply --type-check fails often. Turns out it is the same issue we had
before with esbuild with multiple files. For some reason it doesn't
quite like being parallelized.
Shame.
Fixes #1642

fix --type-check flakiness

---

cli/tests/integration_tests/lit.rs

I have already done this, and it probably got lost somewhere in @honzasp changes of the tests.

Run lit tests on 4xxx ports.

---

api/src/chisel.ts
cli/tests/integration_tests/rust_tests/token_auth.rs
docusaurus/docs/Intro/first.md
server/src/policies.rs

Renaming verbs to methods as that seems more customary. (https://stackoverflow.com/a/49908515/1474847)

Policies: rename verbs to methods.

---

api/src/worker.ts

Fix use of entities in event handlers

---

packages/create-chiselstrike-app/template/Chisel.toml

create-chiselstrike-app: Add 'events' to Chisel.toml template

---

server/src/apply.rs
server/src/lib.rs
server/src/rpc.rs

Isolate type evolution code into a new module (from #1618)

---

.gitignore

Extend .gitignore (from #1618)

---

cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust.rs
cli/tests/integration_tests/rust_tests/token_auth.rs

Prepares ground for removal of `chisel restart` command.

Tests: Replace chisel restart by manual process restarting.

---

cli/tests/integration_tests/lit.rs

I've noticed that while we do increment the ports, they get recycled for lit tests between unoptimized/optimized runs.
This PR fixes that and also bumps the ports 2K higher.

Share ports atomic between lit tests.

---

docusaurus/docs/Intro/data-access.md

Closes https://github.com/chiselstrike/chiselstrike/issues/1655. 
As you can see, the docs I wrote are not exhaustive, but I didn't feel like putting my heart into it as we are likely to remove eagerly loaded relationships.

Write docs on entity relationships.

---

cli/src/main.rs
docusaurus/docs/InDepth/chisel-cli.md

Depends on https://github.com/chiselstrike/chiselstrike/pull/1729 and https://github.com/chiselstrike/chiselstrike/pull/1730

Remove restart command.

---

cli/src/ts.rs
cli/tests/integration_tests/rust_tests/model_defaults.rs

Check that field type and it's default value have matching types.

---

cli/src/cmd/apply/node.rs

use separate .gen files for routes and events

---

packages/create-chiselstrike-app/template/hello.ts

It's better to instruct users to use `ChiselRequest` which is more awesome.

Use ChiselRequest in hello.ts template.

---

cli/tests/integration_tests/framework.rs

As @honzasp noticed, there was an issue in the implementation on `Tee`, where we'd stop writing to the `DuplexStream` if it was full, and not write to it again until we could read again from the reader.
@honzasp suggested that we `select`, but that would mean that we'd need to borrow the buffer mutably twice.
This leaves us with the option of implementing the future ourselves.

fix framework nocapture

---

cli/src/ts.rs
cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust_tests/api_array.rs
server/src/datastore/engine.rs

Adds support for `Date[]` as an entity field.

Add support for arrays of Dates.

---

chiselc/src/parse.rs

Some preliminary legwork for typescript policies. Splits off the emitting part from the compile function

Refactor the compile function

---

cli/tests/integration_tests/rust_tests/api_transactions.rs

An endpoint with an missing await can succeed, if Deno executes the code immediately, or fail, if Deno defers execution. Let's fix up the test assertion to match that.

tests: Fix missing await test

---

server/src/apply.rs
server/src/datastore/crud.rs
server/src/datastore/engine.rs
server/src/datastore/query.rs
server/src/lib.rs
server/src/ops/datastore.rs
server/src/ops/job.rs

This pr is an offspring of my work on policies. It simply make imports a bit tidier.

Tidy imports

---

server/src/apply.rs
server/src/datastore/meta/mod.rs
server/src/datastore/query.rs
server/src/lib.rs
server/src/types/mod.rs

Next pr in getting policies merged: temporarily remove them.

temporarily remove type policies references

---

server/src/policies.rs

Make the regex to really never match.

Improve never matching regex for policy paths.

---

packages/build.rs

Without setting the `NODE_OPTIONS` to `--openssl-legacy-provider`, the build fails for Node 18 with:
error: failed to run custom build command for `packages v0.13.0-dev.0 (chiselstrike/packages)`
Caused by:
process didn't exit successfully: `chiselstrike/target/debug/build/packages-199dc2cd0c8bc6a3/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=./chiselstrike-api/package.json
cargo:rerun-if-changed=./create-chiselstrike-app/index.ts
cargo:rerun-if-changed=./create-chiselstrike-app/template/Chisel.toml
cargo:rerun-if-changed=./create-chiselstrike-app/template/hello.ts
cargo:rerun-if-changed=./create-chiselstrike-app/template/package.json
cargo:rerun-if-changed=./create-chiselstrike-app/template/settings.json …

build: Work around OpenSSL issue in newer Node

---

Cargo.lock
chiselc/Cargo.toml
chiselc/src/policies.rs
chiselc/src/tools/analysis/control_flow.rs
chiselc/src/tools/analysis/d_ir.rs
chiselc/src/tools/analysis/region.rs
chiselc/src/tools/functions.rs

next PR in the series to get TS policies merged.
Changes are made to the policy compiler, to introduce transform, remove evaluation, add some basic error handling, and improvements to parsing. Also fixes some bugs.

chiselc policies

---

api/src/api.ts
api/src/datastore.ts
api/src/type_system.ts
cli/src/ts.rs
cli/tests/integration_tests/rust_tests/model_ids.rs
proto/chisel.proto
server/src/apply.rs
server/src/datastore/crud.rs
server/src/datastore/engine.rs
server/src/ops/type_system.rs
server/src/types/mod.rs
server/src/types/type_system.rs

Adds support for `Id` type which can be used to model relationships.

Implement support for Id field type.

---

cli/src/cmd/dev.rs

Signed-off-by: Piotr Jastrzebski <piotr@chiselstrike.com>

cli: Simplify cmd_dev by using iterators

---

api/src/datastore.ts
cli/tests/integration_tests/rust_tests/model_date.rs

fixes https://github.com/chiselstrike/chiselstrike/issues/1836

Dirty hack filtering by date.

---

chiselc/src/policies.rs
cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust_tests/typescript_policies.rs
server/src/policy/engine.rs
server/src/policy/instances.rs
server/src/policy/mod.rs
server/src/policy/type_policy.rs

This pr replaces the `onSave` transform with two transforms: `onCreate` and `onUpdate`.
Test are updated to reflect this change

replace onWrite transform with onCreate and onUpdate

---

cli/tests/integration_tests/rust_tests/chiselc.rs

Without this test, we wouldn't notice that chiselc is not integrated.

Add an integration test checking that chiselc is working.

---

cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust.rs
cli/tests/integration_tests/rust_tests/api_filtering.rs

Makes sure that mongo-like filtering is tested both in TypeScript and SQL (Rust).

Ensure filter testing

---

cli/tests/integration_tests/framework.rs
cli/tests/integration_tests/rust.rs
cli/tests/integration_tests/rust_tests/chiselc.rs

This PR makes sure that nocapture applies to chisel calls as well (rust integration tests).

Nocapture chisel

---

server/src/kafka.rs

It's easy to trigger the receive failure path. For example, add a topic handler to the `events` directory for a non-existing topic. So let's not kill the server when that happens, but instead, warn about it, which is better behavior for transient falures as well.
Spotted by the `test_kafka_apply` test case that -- for some reason -- started failing on my machine.

server/kafka: Don't kill server on receive failure

---

api/src/datastore.ts
cli/tests/integration_tests/rust_tests/model_date.rs

Add validation for date fields.

---

server/src/datastore/meta/mod.rs
server/src/version.rs

Less verbose startup

---

cli/tests/integration_tests/rust_tests/routing.rs

Format routing test.

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/generate.rs

Thx @honzasp for finding out how to resolve the dprint crate dependency conflicts.

Add formatting step for generated clients.

---

cli/src/cmd/generate.rs
cli/src/cmd/generate_src/client_lib.ts

+ rename cliParams -> Params to satisfy Pekka's OCD.

Add support for User headers on individual requests

---

Cargo.lock
cli/Cargo.toml

Use rustls for reqwest

---

cli/src/ts.rs
cli/tests/integration_tests/rust_tests/model.rs

Print better error message when there are duplicate fields on entity.

---

api/src/filter.ts
api/src/utils.ts
cli/src/cmd/generate_src/client_lib.ts
cli/tests/integration_tests/rust_tests/generate_client.rs

Add support for filtering by Date in clients

---

.github/workflows/rust.yml
cli/tests/common/mod.rs

Followup on https://github.com/chiselstrike/chiselstrike/pull/1974

Remove nightly from CI as it's no longer needed.
