tsc_compile_build/src/lib.rs
If a build.rs ever prints a cargo:rerun-if-changed= pointing to a non
existing file, cargo will rerun that build.rs.
This library is used from other directories, so the relative paths are
wrong, causing tsc_compile to always be rebuilt.
Since this code is using include_str!, the rerun-if-changed was at
most redundant anyway, so drop it.
=> Fix unnecessary rebuilds

server/src/datastore/crud.rs
That way "cargo fmt" can keep it sorted for us.
=> Have a single use block

cli/src/ts.rs, cli/tests/lit/defaults.deno
We forbid expressions for default values, but we should allow unary
expressions. The reason for that, is that things like "-1", that are
obviously very reasonable defaults, are unary expressions.
Fixes #1171
=> Allow unary expression for default values

api/src/chisel.ts
We already do `<T extends ChiselEntity>` in multiple places, this makes it slightly more coherent.
=> Use extends ChiselEntity in multiple places in chisel.ts.

Cargo.lock, cli/Cargo.toml, cli/src/cmd/apply.rs, endpoint_tsc/Cargo.toml, endpoint_tsc/src/chisel-global.d.ts, endpoint_tsc/src/lib.rs, my_tsc/Cargo.toml, my_tsc/src/main.rs
This small crate refactors the special logic for compiling endpoints,
as opposed to plain ts files, to a new crate. This cannot be part of
tsc_compile sice tsc_compile is used to compile api which is used by
the endpoints.
With this my_tsc complies endpoints the same way that "chisel apply"
does.
=> Add the endpoint_compile crate

server/src/datastore/query.rs
=> query.rs: Fix from_ops(...) docstring.

tsc_compile/src/lib.rs
We really just want to remove the JS/TS extensions. In the current
code base both implementations work, but this change makes
without_extension more reliable. For example, given
https://cdn.skypack.dev/handlebars, it used to return
https://cdn.skypack, now it returns the original url.
=> Make without_extension more specific

tsc_compile/src/lib.rs, tsc_compile/tests/output_imported_a.ts, tsc_compile/tests/output_imported_b.ts
This shows that we are not outputting imported files. It will be fixed
in a followup patch.
=> Add a test

cli/tests/integration_tests.rs
The original intent was to add just a newline at the end of the
output. Unfortunately the quoting was wrong and we were writing 3
characters: "'", "\n" and "'".
=> Change CURL to not add single quotes

cli/tests/lit/crud.node, cli/tests/lit/defaults.deno
The first argument to printf is a format string. Passing a single
string is equivalent only if that string has no formatting directives.
=> Add missing format string

cli/tests/lit/introspect.node
If one sees a use of plain curl, it is not clear which difference from
CURL is desired. Using $CURL --no-include makes that explicit.
=> Use $CURL --no-include instead of curl -s

Cargo.lock, cli/Cargo.toml, cli/tests/integration_tests.rs
Showing the whole stdout is very useful for debugging and the current version of lit doesn't show stdout if anything is printed to stderr. :(
=> Upgrade lit to include always_show_stdout flag.

packages/create-chiselstrike-app/package-lock.json, packages/create-chiselstrike-app/package.json
Let's depend on exact versions instead of compatible versions to keep
builds reproducible.
The practical reason is that the current `typescript` dependency
installs latest 4.7.2, which fails the build:
ncc: Using typescript@4.7.2 (local user-provided)
Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
at Object.resolveTypeReferenceDirective (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:42530:18)
at …
=> create-chiselstrike-app: Depend on exact versions

api/src/chisel.ts, cli/tests/lit/aggregations.deno
This is just a TypeScript-side min/max implementation which will be improved later with the propagation of aggregations to backend. It proved to be rather challenging so I've decided to do it in two steps and first have something that works and is testable and improve upon it later.
=> Implement minBy and maxBy TS-side aggregations.

packages/create-chiselstrike-app/template/package.json
The TS we use when compiling is from third_party/deno/cli/tsc/00_typescript.js.
=> Use the same TS version as tsc_compile

cli/src/cmd/apply.rs, cli/src/cmd/apply/deno.rs, cli/src/cmd/apply/node.rs
Make the code more readable by moving Deno and Node mode apply logic
into their own files.
No functional changes, just code movement.
=> cli/apply: Clean up Deno and Node modes

tsc_compile/src/lib.rs, tsc_compile/tests/relative_a/foo.ts, tsc_compile/tests/relative_b/bar.ts
With this we now also test import from sibling directories and test variations on the path of the given source file. The output will change a bit in my next PR, so this serves to make that change more visible.
=> Expand tests

server/Cargo.toml
We don't need that, but doing so avoids a separate compilation of
anyhow. Checked with cargo tree -d.
Also use just 1.0 for the version, since we don't depend on any
specific version.
=> Enable anyhow.backtrace in build-dependencies

tsc_compile/src/lib.rs, tsc_compile/tests/import_js_a.js
In the common case of endpoints/foo.ts importing models/bar.ts, the
output of compile_ts_code would contain "endpoint/foo.ts", but
"file:///path/to/models/bar.ts". That is inconvenient since the
absolute paths will be different in the server.
With this patch we output "endpoint/foo.ts" and "models/bar.ts", which
is the format we want when sending multiple modules to the server.
This also fixes the output path of a top level JS file. A testcase is
included.
=> Output relative paths for local imports

tsc_compile/src/lib.rs, tsc_compile_build/src/tsc.js
TSC is crazy slow to start, so this is a big win:
This speeds chisel apply in a directory with two endpoints by 1.74X
and with 3 by 2.38X.
=> Pass multiple files to TSC itself

cli/tests/lit/secrets.deno
This wraps the output in [], so we know we are always checking the
full output. It also removes the ambiguity between undefined and
"undefined".
=> Improve test

api/src/chisel.ts, cli/tests/lit/secrets.deno
JSON has null, but not undefined, so it is odd to accept JSON but map
null to undefined.
If we really want to keep using undefined for "no secret was set", I can do it, but since that implementation is more complicated I wanted to check first.
=> Don't map null to undefined in getSecret

api/src/chisel.ts, cli/tests/lit/secrets.deno, server/src/deno.rs
It is hard to return undefined from rust, so return our own structure
and map to undefined in JS.
=> Return undefined if there are no secrets

chiselc/src/filtering.rs, chiselc/tests/lit/predicate-indexes.lit
Make sure `chiselc` accepts computed property names, although we cannot
infer filter properties, and therefore no index can be created.
=> chiselc: Add support for computed property names

.gitmodules
We don't need any patches for deno at the moment. We are getting
security warnings from github because the main branch in our fork of
deno is old (which is OK, since we use tags, not the main branch).
With this we should be able to delete the fork. It is easy enough to
create it again if we ever need to.
=> Use upstream deno URL

chiselc/src/query.rs, chiselc/src/rewrite.rs, chiselc/src/transforms/filter.rs, chiselc/src/transforms/find.rs, chiselc/src/transforms/mod.rs, chiselc/src/transforms/utils.rs, chiselc/src/utils.rs, chiselc/tests/lit/filter-properties-findmany.lit, chiselc/tests/lit/filter-properties-findone.lit
This extends `chiselc` to also transform `findMany()` and `findOne()`
with predicate lambdas to internal query calls that are optimized by the
runtime.
Similarly, `chiselc` now also extracts filter properties from `findMany`
and `findOne`, which allows the runtime to auto-index the underlying
table columns if needed.
=> Make chiselc transform find{Many,One} calls

server/src/datastore/crud.rs
This PR does two things.
1) it provides previous/next paging for all pages (even the first one). The rationale is twofold for this. a) it's simpler and b) there actually always can be some results anywhere as new instances can be inserted anytime while paging.
2) It uses the concept of cursor reversal to be able to come back from empty pages (during reversal of a cursor, the direction is reversed and it's made inclusive so that it includes the pivot (last/first element) of the page we came from). 
TODO:
=> CRUD: paging on empty pages

server/src/datastore/engine.rs
Although there is a returning statement in the insert statement, we
are currently not assigning the end result to anything. That indicates
this is an appendage that is no longer needed.
Also, for some unexplained reason that can easily be an sqlx issue,
fetch_one fails in some queries, so the move to execute has an extra
advantage.
(Accidentaly) Fixes #1373
=> execute inserts instead of fetch_one

api/src/endpoint.ts, api/src/worker.ts, cli/tests/lit/endpoint-error.deno, server/src/auth.rs, server/src/deno.rs, server/src/rpc.rs, server/src/server.rs
I am changing the client to send all modules to the server. We don't know which modules are used by which endpoints, just that we have the union of all that is needed.
This PR then changes the server to process all endpoints at once as long as possible, in preparation for getting the auxiliary modules too.
=> Compile multiple endpoints at once

cli/tests/lit/secrets-update.deno, server/src/server.rs
If reading secrets during startup, the last_secrets variable had the
wrong value since it was not aware of the initial secrets. This means
we would never clear the secrets, since last_secrets already thought
they were clear.
This simply removes the attempt at optimizing the secret reading
logic. We can add it back, but in read_secrets, where we can track all
reads, startup and periodic. Before adding it back I would like to see
if it this is actually expensive.
=> Fix clearing secrets

api/src/chisel.ts, chiselc/docs/query-expr.md, chiselc/src/rewrite.rs, chiselc/src/transforms/filter.rs, chiselc/tests/lit/transform-filter.lit, cli/tests/lit/filter-with-predicate.deno
We have __findMany() and findOne() as the other internal function names
so rename __filterWithExpression() to __filter() for consistency and
brevity.
=> api, chiselc: Rename __filterWithExpression() to __filter()

server/src/deno.rs
When the client sends all modules to the server, the module loader
will map from arbitrary Url to the compiled code. Prepare for that by
storing Urls instead of paths.
=> Store Url in the module loader

docusaurus/docs/InDepth/pol.md, docusaurus/docs/Intro/endpoints.md, docusaurus/docs/Intro/first.md
This PR adds coverage of paging to our docs and modifies all examples to reflect the fact that CRUD response has been changed from `[...]` to `{"results": [...]}`.
closes https://github.com/chiselstrike/chiselstrike/issues/1204
closes https://github.com/chiselstrike/chiselstrike/issues/610
=> Update our docs to cover paging.

server/src/main.rs, server/src/server.rs
This exports run_all instead of run_shared_state and
run_on_new_localset, which lets us hide a lot of types.
=> Export less from the server lib

server/src/rpc.rs, server/src/server.rs
With this we only read the endpoints, models and policies once during
startup.
=> Don't reread the initial state

api/src/chisel.ts, chiselc/src/transforms/filter/emit.rs, chiselc/tests/lit/filter_splitting/filter-with-side-effects-return.lit, chiselc/tests/lit/filter_splitting/filter-with-side-effects.lit, chiselc/tests/lit/filter_splitting/findone.ts, cli/tests/lit/entity-findone-filter.deno, cli/tests/lit/find.deno
The `find{Many,One}` methods don't return a `ChiselCursor`, which is why
we can't chain an additional `filter`. Instead, change the internal
functions to take a third parameter -- postPredicate -- that contains
the part of a predicate that may have side-effects.
Bug spotted by Glauber.
=> chiselc: Fix find{One,Many} filter splitting

Cargo.lock, tsc_compile/Cargo.toml, tsc_compile/src/lib.rs, tsc_compile/tests/relative_a/bar.ts
This brings in a fix to make_relative as shown in the testcase. Once a
new version of url is released and we upgrade to a deno that uses it
we can drop this.
=> Update url in tsc_compile

cli/tests/lit/use-ts-moduled.deno
We were never testing that modules are available after a
restart. Currently we always download the modules, but will soon start
sending them from the client and we should check that they are not
lost on restart.
=> Add a missing test

server/src/deno.rs, server/src/rpc.rs
We still cannot drop code downloading because we are not saving those
modules to disk. That is next.
=> Store external modules in the code_map

cli/tests/integration_tests.rs
We were not running the tests in cli/tests/lit/cli
=> Enable tests in subdirectories

cli/tests/lit/cli/describe.deno
In another PR I had a bug that would confuse non endpoint files with endpoints files in "chisel describe". Add a test that would catch that.
=> Expand a test

api/src/worker.ts, server/src/deno.rs
It was used to communicate if the downloaded file should be TSC
compiled or not. The server now never runs TSC, so drop it.
=> Drop dummy .js suffix

api/src/worker.ts, cli/src/cmd/apply.rs, cli/src/main.rs, server/src/deno.rs
This solves the leak caused by never unloading old modules. It also avoids the somewhat surprising behavior that if `http://example.com/some/module.ts` is updated, we don't reload it until a restart. Last but not least, this opens the way to sending models as plain JS modules, which will fix https://github.com/chiselstrike/chiselstrike/issues/1201.
=> Restart on apply

api/src/chisel.ts
This makes the type assertions a lot easier to understand IMHO. It also improves type checking in the internal functions.
=> Split eval ops recursive

api/src/endpoint.ts, tsc_compile_build/src/lib.rs, tsc_compile_build/src/tsc.js
It was already optionally available, but https://deno.land/std@0.144.0/node/module.ts expects to be able to use it without an explicit reference.
=> Make deno unstable API always available at compile time

server/src/rpc.rs
This pr clone the `AddTypeRequest` from the `ChiselApplyRequest` to avoid mutating the original request, as agreed in https://github.com/chiselstrike/chiselstrike/pull/1443#issuecomment-1160103446.
=> clone `AddTypeRequest` before sorting

cli/src/server.rs
We have been hitting timeouts in the bots and I have seen them locally
too.
Some operations, like collecting backtraces in debug builds, are
super slow, so it is not clear if we have a bug causes the server to
be stuck or we just need more time when the system is under load.
An indication that we might just need more time is that I never get a
timeout when running a test in isolation.
=> Use a super long timeout

api/src/worker.ts
The BodyInit in lib.dom.d.ts accepts any ReadableStream. The one in
lib.deno_fetch.d.ts only `ReadableStream<Uint8Array>`.
This changes the code to use `ReadableStream<Uint8Array>` so that it
works with both. On the rust side, op_chisel_read_body returns
ZeroCopyBuf, so this is reasonable.
=> Make type more flexible

api/src/worker.ts
The new version doesn't depend on globalThis.window or the Window type
existing.
This makes it easier to change which .d.ts libraries we use.
=> Make the window in worker hack more flexible

api/src/chisel.ts
This PR finally brings home the typing fixes. It also simplifies the code quite a bit. 
There are still two smaller problems remaining:
1. As a follow-up we can come up with some way to remove the duplication of implementation of most `jsonToOutput` implementations, but I think it can be a follow-up.  
2. The function `jsonToOutput: 
```
jsonToOutput(rawJson: unknown): T {
return this.inner!.jsonToOutput(rawJson);
}
```
has to use the non-undefined `this.inner!` assertion which might be possible to avoid as the only case where this happens is for `BaseEntity`. It would be nice to have this expressed type-wise, but I don't think it's that big of a problem.
=> chisel.ts: Introduce `jsonToOutput` to clean up the code and fix typing issues.

api/src/chisel.ts, api/src/endpoint.ts, api/src/worker.ts, tsc_compile_build/src/lib.rs, tsc_compile_build/src/tsc.js
This is required for being able to import
https://deno.land/std@0.144.0/node/module.ts which requires
lib.deno_web.d.ts which conflicts with lib.dom.d.ts.
We also need to add deno.worker since it defines apis (also defined in
lib.dom.d.ts) used by worker.ts.
=> Remove lib dom

cli/tests/lit/cli/describe.deno
This pr trims the output of `wc -l` in the test `describe.deno`. The test was failing on macos, because its version of `sed` adds padding to the result.
=> trim wc output in test

api/build.rs, api/src/worker.ts, cli/tests/lit/node-std.deno, tsc_compile/src/lib.rs, tsc_compile_build/src/lib.rs, tsc_compile_build/src/tsc.js
We can do this now that we don't use a stand alone tsc to process our
own files.
This allows us to import https://deno.land/std@0.144.0/node/module.ts
Fixes #761
=> Use exactly the same libraries as deno cli

deno.json, tsc_compile_build/src/tsc.js
I forgot to do this when splitting out tsc_compile_build.
=> Enable deno fmt and lint in tsc_compile_build

cli/tests/lit/delete.deno, server/src/datastore/engine.rs, server/src/deno.rs
This PR fixes a bug that was caused because the `op_chisel_entity_delete` method was mutating the DB with its own transaction rather than the current one. This caused SQL to deadlock, and throw an error, as well as break the transactionality guarantee of chiselstrike.
I have also added a test.
close #1482
=> Fix transactionality bug when deleting entity

.gitignore, Cargo.lock, cli/Cargo.toml, cli/tests/common/mod.rs, cli/tests/integration_tests.rs, cli/tests/linters.rs
This PR makes the test install the cargo tool in a custom directory, so we don't mess with the developper rust environment.
=> Install cargo tools in isolated path in tests

server/src/auth.rs, server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/meta/mod.rs, server/src/datastore/query.rs, server/src/deno.rs, server/src/rpc.rs, server/src/types.rs
This PR aims to make our type system more expressive and paves a way for extended typing support (`List`, `Array`, etc.)
There are multiple patches so reviewers are advised to go patch by patch. 
First thing this PR does is it introduces `Type::Entity(Entity)` and standalone `enum Entity {Auth, Custom}` types and makes amendments where necessary for the code to compile. 
Then it renames `add_builtin_object_type` -> `add_auth_type` and `add_type` -> `add_custom_type`.
Finally it brings home the idea and removes the `is_auth` field from `ObjectType` in favor of `Entity::is_auth` convenience method.
=> Introduce `Entity` type covering Custom entity type and Auth types.

cli/tests/lit/pol-loggedin.deno
sed -i behaves differently on linux and macos, found a cross-platform fix.
=> fix failling bug on macos

tsc_compile/src/lib.rs, tsc_compile/tests/hello.ts
Exporting an anonymous function somehow found a bug in another PR I am
writing. This is tested in integration, but having a simple test like
this would have saved some time.
=> Add a simple test

cli/tests/lit/cli/reapply.deno
We didn't have a testcase that tries to redefine AuthUser as a custom type in the `models` directory.  It's
important to catch such cases as we rework the type system.
=> Test attempt to redefine AuthUser

cli/Cargo.toml, cli/src/main.rs, cli/src/ts.rs, cli/tests/lit/types.deno, proto/chisel.proto, server/src/auth.rs, server/src/lib.rs, server/src/rpc.rs
Next PR in the `List` odyssey. 
This PR introduces new protobuf type 
```
message TypeMsg {
oneof type_enum {
bool string = 1;
bool number = 2;
bool bool = 3;
string entity = 4;
};
}
``` 
which represents various type flavors which map nicely to server's `Type` enum. I tried splitting the PR into multiple patches, but unfortunately, the main bulk of changes needs to go all at once to make the for a nice standalone commit.
=> Introduce more expressive type support in protobuf between client and server

cli/tests/common/mod.rs, cli/tests/integration_tests.rs, cli/tests/linters.rs
This pr fixes the failing CI tests, caused by the deno binary not being found.
I still have no explanation as to why the CI passed in the first place.
=> prepend chisel path to PATH when running test binaries

tsc_compile/src/lib.rs, tsc_compile/tests/deno_types_import/a.ts, tsc_compile/tests/deno_types_import/b.d.ts, tsc_compile/tests/deno_types_import/b.js, tsc_compile/tests/deno_types_import/c.ts, tsc_compile_build/src/tsc.js
Support for deno-types is implemented by resolving a reference to a
.js to the corresponding .d.ts. This unfortunately means that if the
.js then references a .ts, we would not compile that .ts.
In the included example, we were not compiling c.ts.
Fix that by passing all the files that deno_graph finds to TSC.
=> Compile all sources in the graph

cli/src/cmd/dev.rs, cli/src/main.rs, cli/src/server.rs
Pass any cli arguments after a `--` to chiseld on  `start` and `dev`
command, e.g:
`chiseld dev -- --help` : prints chiseld help
Followup: 
- I need another PR to make chiselstrike correctly exit when chiseld exits.
- Add test
- Add documentation
=> pass cli args to chiseld

Cargo.lock, cli/Cargo.toml, cli/src/cmd/dev.rs, cli/src/main.rs, cli/src/server.rs
Spawn chiseld command with tokio instead of std.
This allows us to early exit when chiseld exit.
This is necessary for cases where chiseld would exit while chisel is still waiting for it to go up:
```
chisel start -- --help
```
in this case, we were waiting for the server url, before checking if it had exited (https://github.com/chiselstrike/chiselstrike/pull/1523/files#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bL265), basically blocking the process.
followup to #1521
=> spawn chiseld with tokio

cli/src/ts.rs, cli/tests/lit/defaults.deno
This PR fixes accidental regression introduced by https://github.com/chiselstrike/chiselstrike/pull/1503 . 
Originally, we supported models with default-initialized fields without a type. #1503 accidentally regressed the capability requiring all fields to have a type. This PR brings it back and adds a test coverage for it.
=> Deduce type for defaulted fields with no type.

server/src/main.rs, server/src/server.rs
This pr adds a `--show-config` flag on chiseld that outputs the configuration that would be used if the server was run, and then exits.
This is useful for two reason:
- Since we now have support for configuration file, it is helpful to be able to print what is the actual configuration of the instance, accounting for environment variables, config file, and cli arguments
- This will allow us to write test for both configuration files, and config being passed through the cli to chiseld
=> add --show-config cli option

docusaurus/docs/Intro/first.md
User was trying to filter by `.by.name` but his model taken from the example had `.by` of string type. I've fixed the docs a little bit to be more explicit about this in the relationships example.
=> first.md: Modify our relationships CRUD example to prevent missunderstandings.

Cargo.lock, cli/tests/common/mod.rs, server/Cargo.toml, server/tests/test_config_file.rs
add test for configuration file.
I have caught a bug in the library that handle the toml parsing for us in the meantime, and there is already an open PR to fix it https://github.com/dalance/structopt-toml/pull/28. It hasn't been merged in a long time, but I have pinged the owner to see if we can get it merged.
We should probably for this, for safety, until this is merged.
=> chiseld test config file

Cargo.lock, server/Cargo.toml, server/src/introspect.rs
The latest released version of `openapi` crate depends on `serde_yaml`
version 0.7, which has the following uncontrolled recursion but that
Dependabot warns about:
https://github.com/dtolnay/serde-yaml/releases/tag/0.8.4
Upgrade to the latest version of `openapi` in the source repository to
fix the dependency to `serde_yaml` 0.8.
=> Upgrade openapi crate

api/src/chisel.ts
Just a simple reorder of ops constructor arguments so that it's a bit more ergonomic.
=> Reorder args in Ops constructors.

api/src/worker.ts, cli/tests/lit/return.deno, docusaurus/docs/Intro/endpoints.md
We mandate a Response to be returned, meaning that users have to do
returnFromJson, or in other ways construct responses.
However in many cases, specialized endpoints want to return well
defined things like an array of models, a model, or even strings.
Allow that to happen, by converting to a Response internally.
This is a major UX boost that allow us to craft much shorter endpoints
=> api improvements: allow users to return arbitrary types

scripts/centos-devtool
This adds a helper script to start a CentOS 7 container within the
source tree for building releases. Please note that you need to install
prerequisites in the container as per RELEASING.md.
=> scripts: Add centos-devtool helper

.github/workflows/rust.yml, cli/tests/lit/introspect.node
Github hosted runners are struggling with the linters at least, with a
total runtime of 40 minutes per build (!).
We have some beefier self-hosted Github runners so use them instead.
=> Switch to self-hosted runners in CI

Cargo.lock, chiselc/Cargo.toml, chiselc/tests/integration_test.rs
Uses our forked version of lit crate in chiselc, adds convenience `config.always_show_stdout = false;` line.
=> Use our forked version of lit in chiselc

.mergify.yml
Right now, if `main` has changed after tests passed, Mergify will
*merge* `main` and re-run tests. Instead, let's use the `rebase` update
method to get a cleaner git history.
=> Use "rebase" as Mergify update method

server/src/deno.rs
Change the error response from 'ChiselAuth' to 'AuthSecret' to match the web UI text as @dekimir suggested [here](https://github.com/chiselstrike/frontend/issues/486#issuecomment-1171333695)
- https://github.com/chiselstrike/frontend/pull/509
=> refactor(chisel-secret): change the error response

server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/meta/mod.rs, server/src/datastore/query.rs, server/src/deno.rs, server/src/rpc.rs, server/src/types.rs
The `Field`s of an `Entity` have a `type_: Type` field, which makes the
`Type` being reccursive. This makes it impossible to instanciate types
that that cyclic dependency between them (including self-reference).
This PR makes another step towards supporting self-referential Entity,
and cyclic dependency in Entitities
step towards #1448
=> Non-recursive Type

api/src/chisel.ts, chiselc/docs/query-expr.md, chiselc/src/query.rs, chiselc/src/transforms/filter/emit.rs, chiselc/src/transforms/utils.rs, chiselc/tests/lit/filter_splitting/filter-with-side-effects-return.lit, chiselc/tests/lit/filter_splitting/filter-with-side-effects.lit, chiselc/tests/lit/filter_splitting/findone.ts, chiselc/tests/lit/transform-filter.lit, cli/tests/lit/filter-with-predicate.deno, cli/tests/lit/find.deno, server/src/datastore/crud.rs, server/src/datastore/expr.rs, server/src/datastore/query.rs
As agreed ... somewhere with @penberg , I've renamed `Expr::Literal` to `Expr::Value` as it's more fitting and will allow us to compile filtering lambdas that use variables.
=> Rename Expr::Literal to Expr::Value.

api/src/chisel.ts, cli/tests/lit/map.deno, docusaurus/docs/InDepth/cursors.md
map is a classic operation that is provided by Array and frankly many
other primitives.
This simple version executes the code in typescript, but already has
the added advantage of not forcing the full materialization of the array
prior to map, as would be the case with toArray.map().
In the near future we can pass many of these functions to the database.
=> api: adds the map operator

docusaurus/docs/InDepth/chisel-cli.md, server/docs/manual.md
Commit f9bf50bebdc8236eb2e2386961015fd40cbf4837 ("merge meta and query
dbs") deprecated the option so let's remove references to it from
documentation.
Fixes #1369
=> Remove references to "metadata-db-uri" option

cli/tests/lit/unique.deno, server/src/datastore/meta/mod.rs
Fixes unique field migration in the meta DB. It was likely a typo.
=> Fix is_unique fields migration.

cli/tests/lit/cli/describe.deno, cli/tests/lit/filter.deno, cli/tests/lit/find_by.deno, cli/tests/lit/out-of-order-models.deno, cli/tests/lit/return.deno
Because the lit framework is a piece of crap, we weren't checking for errors on multiple places.
`+`  some trailing newlines trimming.
=> Fix missing colon in lit tests.

server/src/secrets.rs, server/src/server.rs, server/tests/test_config_file.rs
make chisel secrets env variable part of the options, with fallback to environment variable. This permits setting them in the config file, and through the CLI.
=> add chisel secret vars to opt

cli/Cargo.toml, server/Cargo.toml
As I was trying to build chisel in a container, I realized that tonic_build had rustfmt feature enabled by default. This needlessly complicates the build process, and newer versions of tonic do not require that anymore.
For now, I have only removed the feature, but it may be desirable to bump tonic later on.
=> remove rustfmt as build dependency in tonic_build

cli/tests/lit/cli/describe.deno, cli/tests/lit/cli/reapply.deno, cli/tests/lit/delete-type.deno, cli/tests/lit/pol-anon.deno, cli/tests/lit/type-evolve.deno, cli/tests/lit/types.deno, server/src/datastore/meta/mod.rs, server/src/rpc.rs
Currently we disallow models to be removed from files at all, because
that can destroy data in the database. Deletion has to happen with
an apply flag.
This is very inconvenient, though, for both local development, where a
user may be just experimenting with types, or hosted chiseltrike, where
apply is automatically done through git, so there is no way to pass
flags.
We should be more tolerant, and allow models to be deleted if they are
empty.
=> allow deletion of empty models

cli/src/ts.rs, cli/tests/lit/type-evolve.deno, server/src/datastore/meta/mod.rs, server/src/types.rs
This PR allow us to write things like:
a: number = Date.now()
in defaults.
We need surprisingly little to make this work, which makes me very
happy. Essentially, Entity.build() will already execute those functions,
so it works just fine.
We just need to make sure that the schema evolution works, which also
happen to work just fine: for complex expressions, we just treat them
as "no defaults". That makes sense, because if you have something like
"Date.now()", the behavior the user expects for things that didn't
exist before is not to retrofill with the current date...
So we allow adding mandatory types with literals and change the error
messages accordingly. Complex expressions behave like no-default.
We do miss the opportunity to allow things like "string".length and "1 +
2", which are …
=> allow arbitrary defaults

packages/create-chiselstrike-app/template/gitignore
Add ".vscode" and ".gen" directories and the ChiselStrike local
development database files to .gitignore as suggested by
@ricardodalarme.
=> create-chiselstrike-app: gitignore template improvements

Cargo.lock, cli/Cargo.toml, cli/tests/integration_tests/framework.rs
Quality of life improvement, this ensures that if chisel apply (or similar) fails with ProcessError, we get a nicely formatted message containing STDOUT and STDERR of the process.
=> rust tests: Pretty print ProcessError.

cli/tests/integration_tests/rust.rs
Shifting the Rust tests to the 40k range to prevent any conflicts with Lit tests.
=> Put Rust integration tests' ports into 40k range.

server/src/internal.rs, server/src/rpc.rs, server/src/server.rs
We always return 200 on the readiness probe, but there are some race
conditions here, due to which it is still possible for the readiness
internal health endpoint to say we are ready to take requests when
in reality we are not.
This increases the granularity and gives us more control over how
we declare whether or not we're ready.
=> granular readiness

docusaurus/docs/InDepth/advanced-data.md
We merged a patch allowing non-literal defaults but didn't update the
documentation.
As it turns out, I asked myself "what if I want a field that gets
updated when the object is updated?", and guess what: just overriding
save works juuuuuust fine.
So document that too.
=> document non-literal defaults

api/src/chisel.ts, cli/tests/integration_tests/lit_tests/crud.node
This is crucial for objects with non-literal defaults. Consider for
example, the following object:
```
export class Joke extends ChiselEntity {
createdAt : number = Date.now()
name : string
content : string
}
```
because "createdAt" has a default, it is convenient not to specify it
when creating the object. However, if you call a CRUD PUT on an existing
object, the whole object gets recreated and have the default it had
before (in this case, a creation time).
With a PATCH, we can pass just name and content, and createdAt will be
left alone.
Fixes #1213
=> CRUD: read object before PUT

Cargo.lock, server/Cargo.toml, server/src/datastore/dbconn.rs
If we re-generate `Cargo.lock`, we get the latest sqlx release, which --
unfortunately -- breaks our SQLite code because we never enable WAL
explicitly.
Let's upgrade sqlx in controlled way by first changing our code, and
then bumping the version.
=> Upgrade sqlx

cli/tests/integration_tests/lit_tests/cli/reapply.deno, docusaurus/docs/InDepth/advanced-data.md, server/src/rpc.rs, server/src/types.rs
Now that we have the transactional infrastructure to make sure a type
is empty, we should allow empty types to be evolved in arbitrary
fashion.
This is especially good QoL for starting projects, in dev mode,
where you may be saving the file constantly.
=> allow arbitrary evolution of empty types.

server/src/deno.rs
We are catching String, but not &str, so anyhow!("some static str")
doesn't get caught.
=> catch extra error type on deno error converter

cli/src/cmd/dev.rs, server/src/server.rs
=> Use tokio::select!() to avoid having to fuse()

cli/tests/integration_tests/database.rs, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust.rs, cli/tests/integration_tests/rust_tests/token_auth.rs, server/src/deno.rs, server/src/policies.rs
A new kind of policy lets you forbid endpoint access without a particular HTTP header that contains the correct secret value.
=> Implement token authentication

.github/workflows/rust.yml
We're having problems with test suite leaving stray `chiseld` processes
running. Let's kill them until we have containerized the thing.
=> github: Kill stray `chiseld` processes

.github/workflows/rust.yml
Tests got stuck in the past, this PR adds a timeout of 20 minutes to test steps in the CI pipeline to limit the impact of stuck tests.
=> Add timeout to test pipelines.

cli/src/ts.rs, server/src/api.rs, server/src/auth.rs, server/src/datastore/crud.rs, server/src/datastore/dbconn.rs, server/src/datastore/engine.rs, server/src/datastore/expr.rs, server/src/datastore/meta/mod.rs, server/src/datastore/meta/schema.rs, server/src/datastore/mod.rs, server/src/datastore/query.rs, server/src/deno.rs, server/src/internal.rs, server/src/introspect.rs, server/src/kafka.rs, server/src/lib.rs, server/src/main.rs, server/src/policies.rs, server/src/prefix_map.rs, server/src/rcmut.rs, server/src/rpc.rs, server/src/runtime.rs, server/src/secrets.rs, server/src/server.rs, server/src/types.rs, server/src/vecmap.rs
We don't have to use `pub(crate)` everywhere, it is sufficient if we apply `pub(crate)` only at the crate root and use just `pub` in modules.
In particular, this does not affect warnings about dead code.
=> Use `pub` instead of `pub(crate)` in server (from #1618)

cli/src/cmd/dev.rs
Let's teach "chisel dev" about the event handler directory so that
changes are hot-reloaded.
=> cli/dev: Track changes in event handlers

cli/src/chisel.rs, cli/src/cmd/apply.rs, cli/src/cmd/apply/deno.rs, cli/src/cmd/apply/node.rs, cli/src/main.rs, cli/src/server.rs, cli/src/ts.rs, server/src/internal.rs, server/src/lib.rs, server/src/rpc.rs
=> Use module `proto` to hold protobuf definitions (from #1618)

api/src/chisel.ts, cli/tests/integration_tests/lit_tests/upsert.deno
This adds an experimental ChiselEntity.upsert() API for performing an
update or a create if no entity exists.
Fixes #1238
=> Upsert API

server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/meta/mod.rs, server/src/datastore/query.rs, server/src/deno.rs, server/src/rpc.rs, server/src/types.rs
In SQL, the statement is `BEGIN TRANSACTION`, there is no need to introduce custom terminology.
=> Use "begin transaction", not "start transaction" (from #1618)

api/src/worker.ts, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust_tests/find.rs, cli/tests/integration_tests/rust_tests/token_auth.rs
When the user returns a plain string from the request handler, it will be serialized as JSON. This is very confusing and also incorrect, because a valid JSON document must be an array or an object.
=> Return strings verbatim, without conversion to JSON (from #1618)

server/src/datastore/dbconn.rs, server/src/datastore/engine.rs, server/src/datastore/meta/mod.rs, server/src/datastore/mod.rs
Make `MetaService` and `QueryEngine` just simple wrappers around `Arc<DbConnection>`. Also, there is no need for the custom `Kind` type.
=> Simplify working with connection pools (from #1618)

server/src/apply.rs, server/src/datastore/meta/mod.rs, server/src/datastore/query.rs, server/src/types/builtin.rs, server/src/types/mod.rs
Replacing compile-time polymorphism with `&dyn` reduces the amount of generated code.
=> Reduce polymorphism in types/mod.rs (from #1618)

docusaurus/docs/Intro/streaming.md
The StringDecoder thing is just ugly and nobody will use that in
real-life code. Switch to equally ugly, yet useful, example with JSON.
=> docs: Switch to JSON-based streaming example

server/src/api.rs, server/src/datastore/meta/mod.rs, server/src/introspect.rs, server/src/policies.rs, server/src/server.rs
`&str` is isomorphic to `T: AsRef<str>`, but does not generate redundant monomorphisations of the same function.
=> Don't use unnecessary polymorphism (from #1618)

api/src/worker.ts, cli/examples/person.ts, cli/tests/integration_tests/lit_tests/aggregations.deno, cli/tests/integration_tests/lit_tests/cli/describe.deno, cli/tests/integration_tests/lit_tests/defaults.deno, cli/tests/integration_tests/lit_tests/filter-with-predicate.deno, cli/tests/integration_tests/lit_tests/filter.deno, cli/tests/integration_tests/lit_tests/pol-anon.deno, cli/tests/integration_tests/lit_tests/populate.deno, cli/tests/integration_tests/lit_tests/sort.deno, cli/tests/integration_tests/lit_tests/store-nested-type.deno, cli/tests/integration_tests/lit_tests/transaction.deno, cli/tests/integration_tests/rust_tests/array.rs, server/src/main.js
In modern JavaScript, it is usually better to use imports rather than a global variable. For example, to type-check code that uses the global variable, we must feed `tsc` with an extra file that specifies the type of the variable. Getting rid of the `Chisel` variable will simplify our code in the fugure.
=> Remove the `Chisel` global variable (from #1618)

.github/build.Dockerfile, .github/workflows/rust.yml
This PR containerizes out pipeline builds to achieve better isolation from Runner's filesystem, stray processes etc.
It's currently based on our Docker image stored in chiselstrike's GH container registry: `ghcr.io/chiselstrike/rust-build-image:v1.0` which was built using `.github/build.Dockerfile`.
The reason why we need to have custom container is that we need to run the tests without root access to test some properties of file access and manipulation. That however doesn't allow us to install the required packages. (I got `sudo not found` error). So we build a container with dependencies and run in it without root. 
I wanted to automatically build the image as a pre-step to our build process, but I'm unable to make it push to our registry so I've deferred it to another PR which doesn't …
=> Containerize Github actions.

docusaurus/package.json
Docusaurus does not work with Node 14, so bump up the engine
requirement.
=> docs: Bump up Node version

cli/tests/integration_tests/rust_tests/policies_auth.rs, cli/tests/integration_tests/rust_tests/policies_loggedin.rs, server/src/policies.rs
In my eagerness to remove all traces of "endpoints" in #1686, I forgot to provide backward compatibility for policies. This PR fixes that and adds tests for this regression.
Perhaps we should be more strict when parsing policies and reject YAMLs that have unknown keys, because if the user makes a typo in their policy, the results might be disastrous, because we will simply ignore the policy and open the backend to everybody on the internet.
Builds on #1712
=> Fix backward compatibility with `endpoints` in policies

cli/tests/integration_tests/rust_tests/auth.rs
chisel.apply() is not needed for auth endpoints to exist.
The testcase for incorrect ChiselAuth value is already covered in
policies_auth.rs.
=> Drop redundant code in rust_tests/auth.rs

packages/create-chiselstrike-app/template/package.json
They are already provided transitively by the CLI package.
=> Removed esbuild and typescript deps from the app template package.json

docusaurus/docs/InDepth/login.md
Completes https://github.com/chiselstrike/chiselstrike/pull/1711#pullrequestreview-1089191606
=> docs: Mention that AuthUser is managed internally

cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust_tests/policies_loggedin.rs
The `Response` object is designed to be opaque and to be accessed only by its methods, which panic with helpful messages when the response is incorrect.
=> Don't expose internals of `Response` in Rust integration tests

.github/workflows/rust.yml, cli/tests/linters.rs
I forgot to do that when I bumped rust to 1.63
=> bump rust nightly

cli/tests/integration_tests/rust_tests/auth.rs, cli/tests/integration_tests/rust_tests/policies_loggedin.rs, server/src/deno.rs
In 5a98be7 we forbade auth-endpoint access without the ChiselAuth
header.  But a bug snuck in where a request WITH that header would
succeed even if CHISELD_AUTH_SECRET was absent.  This patch fixes it by
requiring the header value be strictly equal to the secret value.
A couple of policies_loggedin tests were relying on the buggy behavior
and needed fixing, too.
=> Deny auth endpoints when AUTH_SECRET is absent

server/src/deno.rs
https://github.com/chiselstrike/chiselstrike/pull/1743#discussion_r961494688
Make error messages more user-friendly when ChiselAuth is absent or
incorrect.
No new testcases; there already are tests for this, but they only check
the response status, to avoid fragility when messages evolve.
=> More descriptinve error messages for ChiselAuth

cli/tests/integration_tests/lit.rs, cli/tests/integration_tests/main.rs, cli/tests/integration_tests/suite.rs, cli/tests/linters.rs
This pr adds an optional param to the integration test binary to take a filter expression.
Now you can do
```
cargo t policies
```
instead of
```
cargo t -p cli -- --test policies
```
More than just a convenience, this makes us a bit more compatible with the rust test harness, since the first command used to fail, because integration did not support this interface.
also rename the linters test module from `test` to `linters`, to make filtering easier, if you want to run the  linter tests, you do:
```
cargo t linters
```
=> add optional filter param for integration

cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/main.rs, cli/tests/integration_tests/rust.rs
adds a `nocapture` flag to the test framework. This flag is compliant with rust test interface, and can be passed like so:
```
cargo test -- --nocapture
```
When it is raised, all output from chiseld is echoed to stdout.
=> add nocapture to test framework

cli/src/ts.rs, cli/tests/integration_tests/rust_tests/model.rs
Splinter of #1618 . Brings back type inference from field initializer, eg: 
```
class Foo {
bar = "Hello World";
}
```
I've also added a patch that tries to wrap errors with swc_error using a macro, but it feels a little messy. Although the error messages will be better :man_shrugging:
=> Make type annotations optional again

server/src/datastore/engine.rs
The "fallback" argument is a type, not an identifier. Noticed the latent
bug while attempting to pass a Vec<u8>.
=> Fix convert_to_argument() macro argument type

README.md
npx does not work with paths
In Node 14.x CLI documentation it's unclear that it's valid to pass a path to a package, however I've tested it and it seems to work as documented by Node 16.x documentation:  
https://nodejs.org/docs/latest-v16.x/api/cli.html#command-line-api
=> Replace npx with node in README

api/build.rs, api/src/datastore.ts, api/src/lib.rs, api/src/type_system.ts, cli/src/ts.rs, cli/tests/integration_tests/rust_tests/model_date.rs, proto/chisel.proto, server/src/apply.rs, server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/ops/mod.rs, server/src/ops/type_system.rs, server/src/types/builtin.rs, server/src/types/mod.rs, server/src/types/type_system.rs
This PR can perhaps be simplified if we merge https://github.com/chiselstrike/chiselstrike/pull/1780 first :thinking: 
That would completely remove the necessity to propagate the type system to TypeScript... Although it feels kinda beneficial anyway because of the proper initialization of nested entities. But it still might be better to decouple the two.
=> Propagate TypeSystem to JavaScript and add Date support.

packages/create-chiselstrike-app/index.ts, packages/create-chiselstrike-app/template/Dockerfile, packages/create-chiselstrike-app/template/README-template.md, packages/create-chiselstrike-app/template/dockerignore
This adds Dockerfile generation to `create-chiselstrike-app`, which allows developers to build an image of their application and its dependencies, including ChiselStrike, to easily deploy to applications to Kubernetes, Fly.io, and other services.
Please note that the Dockerfile only exports port 8080, which means that there's no access to the ChiselStrike RPC from outside. We can re-visit the decision once we have TLS support for gRPC:
https://github.com/chiselstrike/chiselstrike/issues/1782
Also note that the generated image is pretty big because we need to run `npm install` to fetch dependencies, which requires Node to be present. The `chisel apply` command also has a hard-coded dependency to `npx`.
Also, we're currently unable to use Alpine Linux, for example, as a super-slim base …
=> create-chiselstrike-app: Generate Dockerfile

.gitmodules, Cargo.lock, Cargo.toml, api/src/main.js, cli/src/cmd/apply/node.rs, cli/tests/integration_tests/rust_tests/imports.rs, deno_std/Cargo.toml, deno_std/build.rs, deno_std/src/lib.rs, server/Cargo.toml, server/src/module_loader.rs, server/src/ops/env.rs, server/src/ops/mod.rs, server/src/worker.rs
In short, this PR implements `require('buffer')`.
---
In more detail, this PR:
- Embeds the Deno standard library under internal URL `chisel://deno-std/`
- Adds a crate `deno_std`, which transpiles the library using swc (wrapped in `deno_ast` for convenience). I decided to use swc instead of our `tsc_compile`, because swc is faster, simpler and in the future, I would like to use swc in `chisel apply` anyway.
- The sources of the Deno standard library are vendored as a submodule in the repo. We should keep `third_party/deno_std` in sync with `third_party/deno`.
- Resolves Node global imports such as `'buffer'` into Node polyfills from the Deno standard library.
- Implements fake env and cwd, because npm packages often try to read from them.
=> Import polyfills in place of Node standard modules

cli/src/cmd/apply/node.rs
The "esbuild" program is a native binary. Let's run it without "npx" to eliminate the Node.js dependency in "chisel apply".
=> cli/apply: Run "esbuild" without "npx"

api/src/datastore.ts, server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/mod.rs, server/src/datastore/query.rs, server/src/datastore/value.rs, server/src/ops/datastore.rs, server/src/ops/mod.rs, server/src/policies.rs
Introduces `EntityValue` paving way for #1785 . `EntityValue` is used to provide natural transition layer between JavaScript and Rust (and back).
=> Entity value

deno_std/build.rs
1. When the `third_party/deno_std` directory does not contain any modules, fail the build. This may happen when the developer did not update git submodules, for example.
2. Rerun the build script when new files are added to that directory or any of its non-ignored subdirectories. This makes sure that when the developer updates the git submodules, we pick the new source files.
=> Make deno_std/build.rs more robust

tsc_compile/src/lib.rs, tsc_compile_build/src/tsc.js
Fix the tsc_compile_build configuration to not remove comments so that we preserve ChiselStrike API TypeDoc.
Reported by Doug Stevenson.
=> tsc_compile_build: Don't remove comments

api/src/api.ts, api/src/builtin_root.ts, api/src/crud.ts, api/src/datastore.ts, cli/tests/integration_tests/lit_tests/crud-custom.node, cli/tests/integration_tests/lit_tests/delete.deno, cli/tests/integration_tests/lit_tests/echo-endpoint.deno, cli/tests/integration_tests/lit_tests/introspect.node, cli/tests/integration_tests/lit_tests/prefix.deno, cli/tests/integration_tests/rust_tests/crud.rs, server/src/datastore/crud.rs, server/src/ops/datastore.rs, server/src/worker.rs
This PR changes the TypeScript CRUD API. The simple `Entity.crud()` call behaves the same, but the customization is now different. Please see the `crud()` function in `crud.ts` for details (the diff is meaningless, please see the new file directly).
It also changes the paging links in the CRUD API to relative, because it is impossible to provide correct absolute URLs in the general case.
This is a follow-up of #1618.
=> New CRUD API

server/src/rpc.rs, server/src/server.rs, server/src/version.rs
Before this change, `chiseld` would print "Version X is ready" two times during each apply, which is confusing. Let's log the first message, from the "canary" version, as debug, so that it's not shown by default.
=> Don't visibly log when a canary version is ready

api/src/crud.ts, api/src/datastore.ts, api/src/utils.ts, cli/tests/integration_tests/rust_tests/model_date.rs, server/src/datastore/engine.rs
The fix seems to break the test which means that the `EntityValue::to_v8` method doesn't work as it should.
It looks that when the `v8::Value` of `Date` gets to our function, it's just a plain Object and we can't tell it apart by `is_date` method :(.
The reason why it worked so far is that because of CRUD - JSON we must accept float as well from there.
The fix consists of replacing all `mergeDeep` with `buildEntity` and `mergeIntoEntity` which are datastore functions leveraging the recently introduced `typeSystem` data to reflect over the types that are being built. Note that the functions are more or less just a copy of the `populateEntity` method, that was already there.
=> Fix Date's storage and replace `mergeDeep` with proper reflection-based building

Cargo.lock, api/src/crud.ts, api/src/datastore.ts, api/src/http.ts, api/src/kafka.ts, api/src/run.ts, cli/tests/integration_tests/rust_tests/policies_loggedin.rs, server/Cargo.toml, server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/expr.rs, server/src/datastore/meta/mod.rs, server/src/datastore/mod.rs, server/src/datastore/query.rs, server/src/ops/datastore.rs, server/src/ops/job.rs, server/src/ops/job_context.rs, server/src/ops/mod.rs, server/src/policies.rs, server/src/types/builtin.rs, server/src/types/type_system.rs, server/src/worker.rs
this PR introduces new data structures to decouple the runtime from the data layer. Doing so solves some flaws that the current design presented:
- the `DataContext` represents a transactional unit. It is created when a transaction is started by typescript and lives until it is committed or discarded later. It contains all the necessary data for the data layer to operate.
- The `JobContext` is a deno resource that spans the lifetime of a job and contains the data that a job will need to access in its lifetime. This simplifies the management of resources.
- The SQL transaction is not leaked into the runtime anymore, and the concept of the transaction is abstracted away.
- Implicit transactions are not supported anymore. It is always to the consumer of the data layer APIs to provide one, in …
=> Introduce DataContext

.ignore
The `.ignore` file is used by tools like `fd` or `ripgrep` to ignore path for search. The `third_party` directory clutters the search with useless results, all while making search a lot longer. This is a QOL improvement.
=> add .ignore file

server/src/server.rs
`last_try_was_failure` variable was supposed to be used to avoid spamming logs with warnings about failed secrets updates. This was achieved by not logging a warning if the previous try to update the secrets was also a failure.
The problem is that the variable is never set to `false` again while it should be after a successful secrets update. That means the warning won't me logged more than once even in situation like this:
update failed, 1000 x update succeeded, update failed
Signed-off-by: Piotr Jastrzebski <piotr@chiselstrike.com>
=> server: Reset `last_try_was_failure` on success

Cargo.lock, chiselc/Cargo.toml, chiselc/src/main.rs, cli/Cargo.toml, cli/src/main.rs, cli/tests/integration_tests/main.rs
This series partially migrates the source code from [structopt](https://crates.io/crates/structopt) (which self-declared itself as maintenance mode only) to [clap](https://crates.io/crates/clap). `server/` path is not yet migrated, because it also relies on `StructOptToml` crate, and we need to preserve the ability to serialize/deserialize toml structs.
Refs #1777
=> Migrating from structopt to clap

Cargo.lock, api/src/datastore.ts, api/src/type_system.ts, cli/Cargo.toml, cli/src/ts.rs, cli/tests/integration_tests/rust_tests/model_array_buffer.rs, proto/chisel.proto, server/Cargo.toml, server/src/apply.rs, server/src/datastore/crud.rs, server/src/datastore/engine.rs, server/src/datastore/query.rs, server/src/datastore/value.rs, server/src/ops/type_system.rs, server/src/types/builtin.rs, server/src/types/mod.rs, server/src/types/type_system.rs
This PR brings the support for `ArrayBuffer` type as Entity field.
Some notes:
- TS is perfectly fine assigning `ArrayBufferView` to `ArrayBuffer`. Luckily I was able to handle that case as well so no problem :relaxed: It's really unexpected behavior though...
- In CRUD, the ArrayBuffer is encoded with `base64`.
- The base64 encoding is handled well on the way out, but in `POST/PUT` endpoints, it's a bit tricky as there, the json goes through `Entity.build(...)` which meant I had to add ugly hack to the `mergeSourceIntoEntity` function. 
- The `mergeSourceIntoEntity` is becoming rather hairy and I think it will be necessary to refactor it in consequent PR.
=> Support for Array buffer

cli/src/routes.rs, cli/tests/integration_tests/rust_tests/routing.rs
Don't panic in add_route but return Result<()> instead. Use "" instead of r#""# in tests.
Signed-off-by: Piotr Jastrzebski <piotr@chiselstrike.com>
=> cli: Clean up FileRouteMap::add_route and its tests

api/src/datastore.ts
This PR checks that the type of the argument passed to the `restrictionsToFilterExpr` is in fact an object. If it wasn't it would wipe out the database.
=> TS api: runtime check argument type for delete

cli/src/cmd.rs, cli/src/cmd/generate.rs, cli/src/main.rs
This adds a `chisel generate` command that generates types that can be
used from client code to simplify accessing ChiselStrike endpoints.
Currently, the command generates types based on the entities. For
example, given the following entity:
```typescript
export class Message extends ChiselEntity {
sender: string;
body: string;
timestamp: string;
}
```
The command generates the following types:
```typescript
export type Message = {
id: string;
sender: string;
body: string;
timestamp: string;
}
export type Results<T> = {
next_page: string;
prev_page: string;
results: T[];
}
```
The `Message` type maps to the `Message` entity directly. The
`Results<T>` type is the output of a CRUD endpoint that returns multiple
entities.
In the future, if we change the endpoint API to have more types, this …
=> Add `chisel generate` command

Cargo.lock, chiselc/src/policies.rs, server/Cargo.toml, server/src/datastore/expr.rs, server/src/datastore/value.rs, server/src/lib.rs, server/src/policy/engine.rs, server/src/policy/instances.rs, server/src/policy/interpreter.rs, server/src/policy/mod.rs, server/src/policy/store.rs, server/src/policy/type_policy.rs, server/src/policy/utils.rs
This pr introduces the Typescript policy engine.
Right now, this is not connected to anything, so it does nothing.
Internally, the policy engine has two interpreters:
- the boa interpreter: a lightweigth js runtime
- the predicate interpreter, that transforms predicate expressions into `datastore::Expr`.
The `PolicyEngine` is not `Sync` nor `Send`, therefore, each worker has to instanciate it's own, and load it from the policy sources.
Policies for a type are lazily loaded into a `PolicyEvalInstance`. Such instances are cached for the duration of the `PolicyContext`.
The `PolicyProcessor` is used to evaluate a policy on an `EntityValue` instance.
=> Typescript policy engine

packages/create-chiselstrike-app/index.ts
We need to generate `.gitkeep` to potentially empty directories so that `git add` adds them to git repositories.
=> create-chiselstrike-app: Generate more .gitkeeps

.github/workflows/rust.yml, cli/tests/integration_tests/chisel-macros/src/lib.rs, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust.rs, cli/tests/integration_tests/rust_tests/kafka.rs, cli/tests/integration_tests/suite.rs
This paves way for having multiple test cases that use their own topics
for test isolation.
Please note that the created topics are not deleted after test run
because rskafka does not support it:
https://github.com/influxdata/rskafka/issues/190
=> tests: Create Kafka topic in test

api/src/kafka.ts, api/src/run.ts, cli/src/codegen.rs, server/src/internal.rs, server/src/kafka.rs, server/src/lib.rs, server/src/nursery.rs, server/src/ops/kafka.rs, server/src/server.rs, server/src/trunk.rs
Introduce the `Nursery` to abstract away the common pattern of awaiting a dynamic set of futures. This unifies the manual polling in `Trunk` and the suboptimal code in `KafkaService`.
=> Introduce Nursery

Cargo.lock, server/Cargo.toml, server/src/authentication.rs, server/src/authorization.rs, server/src/datastore/mod.rs, server/src/datastore/query.rs, server/src/error.rs, server/src/http.rs, server/src/lib.rs, server/src/ops/job.rs, server/src/ops/job_context.rs, server/src/policy/engine.rs, server/src/server.rs, server/src/types/builtin.rs
This PR introduces support for JWT in typescript policies.
JWT are passed in the the `Authorization: Bearer <TOKEN>` header of the request.
A public signature verification must be passed in the `CHISEL_JWT_KEY`. The key must be a valid RSA PEM key, that is stripped of its header and footer, and all lines concatenated: eg
```
-----BEGIN PUBLIC KEY-----
kasfgfaksdfjlkajshfasd
fjkhaskldjfhaskljhdfka
-----END PUBLIC KEY-----
```
becomes:
```
kasfgfaksdfjlkajshfasdfjkhaskldjfhaskljhdfka
```
The algorithm being used to sign the keys is `RS256`.
All of these format and algorithm choices have been made to work out of the box with Clerk. Additional algorithm and key format could be added in the future.
The token can contain arbitrary user data.
If the token is validated, then it is accessible to …
=> Enable jwt in typescript policies

chiselc/src/parse.rs, chiselc/src/policies.rs
This fixes a bug where swc would panic when emiting code, because it is not passed the `SourceMap` that was used for parsing. This is fixed by passing to the emmiter the same `SourceMap` that was used for parsing.
=> Policies: pass SourceMap to emit js

cli/tests/integration_tests/lit_tests/stream-db.deno
This PR fixes the stream-db.deno test by making sure that all the writes are performed sequentially.
I found this when working on an implementation of `add_row` that had more than one `await` point. Awaiting the promises concurrently gives no guarantees that the insert will be performed in order.
=> fix stream-db.deno test

server/src/policy/debug.rs, server/src/policy/engine.rs, server/src/policy/mod.rs
This PR exposes a host function to the policy runtime to debug values.
it is called as follow:
```typescript
(entity, ctx) => {
debug(entity);
}
```
depends on #1876
=> Policies: expose debug function

chiselc/src/tools/analysis/control_flow.rs, chiselc/src/tools/analysis/region.rs, chiselc/src/tools/functions.rs
This PR makes improvements to the controlflow analysis, and particularly to the Region analysis:
- Fix a couple of bugs
- Add documentation
- Add tests
- make region building more generic for testing
- add invariant assertions
- disable loop support (it was not supported anyways, and need additional work to work properly)
=> Improve ControlFlow analysis

.github/workflows/rust.yml, Cargo.lock, api/src/api.ts, api/src/kafka.ts, api/src/run.ts, cli/tests/integration_tests/rust_tests/kafka.rs, server/Cargo.toml, server/src/kafka.rs, server/src/lib.rs, server/src/ops/job.rs, server/src/ops/kafka.rs, server/src/ops/mod.rs, server/src/outbox.rs, server/src/types/builtin.rs, server/src/version.rs, server/src/worker.rs
This pull request implements support for publishing events on a Kafka
topic.
The high-level API looks as follows:
```typescript
import { publishEvent } from "@chiselstrike/api";
await publishEvent({
topic: "topic",
key: "hello, key",
value: "hello, value"
});
```
Internally, the `publishEvent()` function writes to an `Outbox` entity.
As the write participates in the same transaction of the call-site, you
essentially get transactional event publishing. If the transaction rolls
back, the event is never sent out. However, if the transaction commits,
events in the `Outbox` entity are eventually published on a Kafka topic.
The way we implement transactional event publishing is called the
"outbox pattern" and it has one downside: instead of Kafka's
exactly-once semantics, outbox pattern only …
=> Kafka event publishing

packages/create-chiselstrike-app/template/Dockerfile
There are many platforms around where you may want to deploy ChiselStrike where there is no local volume (one real example: digital ocean). For those, we have to pass an environment variable with a connection string for an external database.
The ARG statement for Dockerfile allows us to have a default, so we can default to a local image, meaning it will still work when no arguments are passed. But this opens the door for users to use external databases more easily.
=> improve Dockerfile for project template

api/src/datastore.ts, api/src/filter.ts, cli/tests/integration_tests/rust_tests/api_find.rs
As requested by @CodingDoug , this PR brings support for FilterExpr to both findMany and findOne functions in the TS API. I've also made the filterExpr a little bit stricter so that it doesn't accept filters for keys which are not part of the entity.
=> Add support for FilterExpr in find_many and find_one.

README.md
We need to specify a version; otherwise a random version cached on someones machine could be picked up.
=> Fix `npx create-chiselstrike-app` command in README.md

packages/create-chiselstrike-app/template/gitignore
Ignore the `.eventgen` folder when running `create-chiselstrike-app`
=> fix(create-chiselstrike-app): ignote generated events folder

.github/workflows/rust.yml, Cargo.lock, api/src/crud.ts, api/src/datastore.ts, api/src/routing.ts, api/src/special.ts, api/src/type_system.ts, cli/Cargo.toml, cli/src/cmd/generate.rs, cli/src/cmd/generate_src/client.ts, cli/src/cmd/generate_src/client_lib.ts, cli/src/cmd/generate_src/reflection.ts, cli/src/main.rs, cli/tests/common/mod.rs, cli/tests/integration_tests/chisel-macros/src/lib.rs, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust.rs, cli/tests/integration_tests/rust_tests/crud.rs, cli/tests/integration_tests/rust_tests/generate_client.rs, cli/tests/integration_tests/rust_tests/routing.rs, cli/tests/integration_tests/suite.rs, cli/tests/linters.rs, deno.json, server/Cargo.toml, server/src/datastore/crud.rs, utils/Cargo.toml
This PR brings support for client generation.
The main changes include
- New build container to include `ts-node`. 
- `chisel generate` generates TS client that can be used against our CRUD endpoints
- `/__chiselstrike/routes` internal reflection endpoint returning information about routing
- Added support for testing of generated clients to our rust integration tests.
=> Generate clients

api/src/api.ts, api/src/crud.ts
To import these files you needed to import from the file. Example:
```ts
import type { EventHandler } from '@chiselstrike/api/lib/kafka.ts';
```
Now allow to import it from `@/chiselstrike/api`
=> feat(api): expose EventHandler, ResponseLike and ChiselEntityClass

cli/src/cmd/generate.rs, cli/src/cmd/generate_src/client_lib.ts, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust_tests/generate_client.rs
In this PR, I have done the following:
- Enabled type checking for client tests and fixed the corresponding bugs that were found.
- Implemented and activated entityToJson() to perform the inverse operation of jsonToEntity().
- Introduced and used OmitRecursively for the post() function to allow the submission of entities and nested entities without an ID.
- Added tests covering the .post() function with all types that we provide (with the exception of ArrayBuffer, which will require a separate PR).
=> Improve test coverage of clients and fix found bugs

api/src/api.ts
Fix `Action` being exported as a type, which made the linter unhappy
=> export Action as value

.github/build.Dockerfile, .github/workflows/rust.yml, cli/tests/integration_tests/framework.rs, cli/tests/integration_tests/rust.rs, cli/tests/linters.rs
Gets rid of cargo_install for deno in our tests in favor of deno preinstalled in a docker. 
This makes test execution faster. Rough estimate: general build plus tests 18 -> 14 minutes, postgres tests 9 -> 7 minutes
=> Use deno from docker instead of installing it.

api/src/utils.ts, cli/tests/integration_tests/rust_tests/generate_client.rs
This function turns any JavaScript value to JSON while converting values like ArrayBuffer and Date into chiselstrike compatible format. (e.g. ArrayBuffer is turned into base64 encoded string).
Usage of this function in `responseFromJson` fixes the issue of CRUD endpoints returning ArrayBuffer and Date in wrong format.
=> Implement and use `valueToJson` function.

cli/src/cmd/generate.rs, cli/src/cmd/generate_src/client.ts, cli/src/cmd/generate_src/client_lib.ts, cli/src/cmd/generate_src/models_without_id.ts, cli/tests/integration_tests/rust_tests/generate_client.rs
+ It fixes a bug in client's PUT where the function would throw an error if an ID wasn't provided.
Example generated `models_without_id.ts`:
```
import * as Ωmodels from "./models";
type ΩIfEquals<T, U, Y = unknown, N = never> = (<G>() => G extends T ? 1 : 2) extends (<G>() => G extends U ? 1 : 2) ? Y
: N;
export type Animal = {
kind: string;
};
export type Person = {
name: string;
};
export type ΩWithoutId<ΩEntityType> = ΩIfEquals<
ΩEntityType,
Ωmodels.Person,
Person,
ΩIfEquals<ΩEntityType, Ωmodels.Animal, Animal, never>
>;
```
=> Cli generation: Add dedicated models without ID field.

chiselc/src/tools/analysis/region.rs, cli/tests/integration_tests/rust_tests/typescript_policies.rs, server/src/policy/interpreter.rs
This pr fixes a bug in the policies variable resolver that would return None on a lookup for an unexisting value in a header.
This is not a _very robust_ fix though. A more robust fix would differentiate between static properties and computed properties. We should aim a better compat with js.
=> policies: fix lookup unexisting value

.github/workflows/rust.yml, cli/src/cmd/generate_src/client_lib.ts, cli/tests/integration_tests/framework.rs, package-lock.json, package.json
Trying to bypass CI errors:
```
npm install -g ts-node
3
shell: sh -e {0}
4
env:
5
CARGO_TERM_COLOR: always
6
REGISTRY: ghcr.io
7
IMAGE_NAME: chiselstrike/chiselstrike
8
nightly-version: nightly-2022-08-29
9
POSTGRES_PASSWORD: postgres
10
CACHE_ON_FAILURE: false
11
CARGO_INCREMENTAL: 0
12
npm ERR! code ENOTEMPTY
13
npm ERR! syscall rename
14
npm ERR! path /__w/_tool/node/18.12.1/x64/lib/node_modules/ts-node
15
npm ERR! dest /__w/_tool/node/18.12.1/x64/lib/node_modules/.ts-node-eog8Xbci
16
npm ERR! errno -39
17
npm ERR! ENOTEMPTY: directory not empty, rename '/__w/_tool/node/18.12.1/x64/lib/node_modules/ts-node' -> '/__w/_tool/node/18.12.1/x64/lib/node_modules/.ts-node-eog8Xbci'
```
This patch uses local installation of `ts-node`. 
I had to convert URL to string explicitly because for some …
=> Make tests use local installtion of ts-node.

Cargo.lock, chiselc/Cargo.toml, chiselc/src/policies.rs, chiselc/src/tools/functions.rs, server/src/policy/engine.rs
This pr fixes a bug when converting from a `Cond` to a `Bool`. I was ignoring that And and Or bool can have more than 2 predicates.
I have added property testing to ensure this doesn't regress
=> fix convert cond to bool

cli/tests/linters.rs
As previously discussed, we can probably drop these linters as they are slow and not as important.
It's quite sufficient to run them just once in a while.
=> Drop udeps and sorted deps cargo linters to speed up test suite.

.github/workflows/rust.yml
```
Swatinem/rust-cache@v1 -> Swatinem/rust-cache@v2
actions/cache@v2 -> actions/cache@v3
actions-rs/toolchain@v1 -> dtolnay/rust-toolchain
```
Apart from general upgrade goodness, this should rid us of the deprecation warnings 
```
kafka-test
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, Swatinem/rust-cache@v1, actions/cache@v2
```
Unfortunately, `actions-rs/toolchain@v1` had top be ditched for it seems to be unmaintained (https://github.com/actions-rs/toolchain/issues/221)
=> Upgrade CI actions.
